steps:
  # Install dependencies
  - name: python:3.8-slim-buster
# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-north1-docker.pkg.dev/$PROJECT_ID/$_REPO/retrain:$SHORT_SHA', '.']
    timeout: 600s
 # Docker push to Google Artifact Registry  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'europe-north1-docker.pkg.dev/$PROJECT_ID/$_REPO/retrain:$SHORT_SHA']
    timeout: 600s
images:
  - europe-north1-docker.pkg.dev/$PROJECT_ID/$_REPO/retrain:$SHORT_SHA
timeout: 1800s