name: convergence-env

dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib 
  - pytest
  - pyyaml
  - flask
  - seaborn
  - plotly
  - sqlalchemy
  - pymysql
  - pvlib::pvlib
  - conda-forge::siphon
 
